### ISSUE TITLE
Game crash when equipping thrown item

### ISSUE THREAD

**Issue by esranzarnath** [InfraArcana/ia#88]
In the latest development version, the game sometimes crashes when equipping a throwing weapon. Specifically, it crashes when you open the menu to select a throwing weapon, before it shows the menu.  Testing shows this happens when the player has too many items in their inventory at the time they open the select thrown weapon menu. This appears to be because it lacks the functionality to display a second page of items, 
Simplest way to reproduce is to greatly increase the number of items generated, and then pick up the items one by one, testing the thrown weapon selection until it breaks.

**Comment by InfraArcana** [comment]
Great, thanks for reporting this!

**Comment by InfraArcana** [comment]
This has been fixed
